export const LINKS = [
  "introduction",
  "map",
  "demographics",
  "exhibitions",
  "word-cloud",
  "gallery-spaces",
  "finding-shows",
  "conclusions",
  "studio-visits",
  "sales",
  "sales-cloud",
  // "sales-platforms-cloud",
  "sales-mediums-cloud",
  "cities-neighborhoods-cloud",
  "studio-visitors-cloud",
];

export const STUDIO_VISITORS = [
  { name: "Other artists", value: 46 },
  { name: "Family / non-artist friends", value: 30 },
  { name: "Gallerists / curators", value: 21 },
  { name: "Amateur / new collectors", value: 19 },
  { name: "BFA / MFA peers", value: 13 },
  { name: "Established / experienced collectors", value: 13 },
  { name: "Former / current faculty", value: 10 },
  { name: "Open studios", value: 2 },
  { name: "students", value: 2 },
  { name: "Community members", value: 1 },
  { name: "general public", value: 1 },
  { name: "na", value: 1 },
  { name: "Press", value: 1 },
]

export const SIDE_NOTES = {
  "word-cloud": "* relative size of words based on how many times they appeared in survey responses",
  "gallery-spaces": "* relative size of words based on how many times they appeared in survey responses",
  "finding-shows": "* relative size of words based on how many times they appeared in survey responses",
}

export const CITIES_NEIGHBORHOODS = [
  { name: 'Albany (CA)', value: 1 },
  { name: 'Albuquerque', value: 2 },
  { name: 'Altadena (CA)', value: 1 },
  { name: 'Anchorage', value: 1 },
  { name: 'Atlanta', value: 1 },
  { name: 'Bakersfield', value: 1 },
  { name: 'Baltimore', value: 2 },
  { name: 'Baton Rouge (LA)', value: 1 },
  { name: 'Beacon', value: 1 },
  { name: 'Berkeley', value: 2 },
  { name: 'Bloomington', value: 1 },
  { name: 'Bronx Nyc', value: 1 },
  { name: 'Brooklyn', value: 3 },
  { name: 'Buffalo', value: 1 },
  { name: 'Capitola', value: 1 },
  { name: 'Carlisle', value: 1 },
  { name: 'Central Phoenix', value: 1 },
  { name: 'Chesterfield', value: 1 },
  { name: 'Chicago', value: 2 },
  { name: 'Chippewa Falls', value: 1 },
  { name: 'Columbus', value: 3 },
  { name: 'Congress Heights (DC)', value: 1 },
  { name: 'Coral Springs (FL)', value: 1 },
  { name: 'Corktown', value: 1 },
  { name: 'Creston', value: 1 },
  { name: 'Decline To Say', value: 1 },
  { name: 'Detroit', value: 1 },
  { name: 'Downtown Lexington', value: 1 },
  { name: 'East Palo Alto', value: 1 },
  { name: 'Eastside', value: 1 },
  { name: 'Echo Park', value: 3 },
  { name: 'Edgewood', value: 1 },
  { name: 'Fayetteville', value: 1 },
  { name: 'Florida Indian Beach', value: 1 },
  { name: 'Grand Rapids', value: 1 },
  { name: 'Jacksonville', value: 1 },
  { name: 'Kihei', value: 1 },
  { name: 'Knights Bridge', value: 1 },
  { name: 'Knoxville', value: 1 },
  { name: 'Lafayette', value: 1 },
  { name: 'Lake Ann (MI)', value: 1 },
  { name: 'Lake Toxaway', value: 1 },
  { name: 'Lake Zurich', value: 1 },
  { name: 'Lincoln Heights', value: 1 },
  { name: 'Long Beach', value: 1 },
  { name: 'Los Angeles', value: 6 },
  { name: 'Macalester-Groveland (MN)', value: 1 },
  { name: 'Madison', value: 2 },
  { name: 'Malvern', value: 1 },
  { name: 'Massey Hill', value: 1 },
  { name: 'Maui', value: 1 },
  { name: 'Meredith (NH)', value: 1 },
  { name: 'Miami', value: 1 },
  { name: 'Mile End Montreal', value: 1 },
  { name: 'Milo-Grogan', value: 1 },
  { name: 'Milwaukee', value: 2 },
  { name: 'Monroe Ward', value: 1 },
  { name: 'Monrovia', value: 1 },
  { name: 'Murray', value: 1 },
  { name: 'Nashville', value: 1 },
  { name: 'Natomas', value: 2 },
  { name: 'New Brighton State Beach', value: 1 },
  { name: 'New Haven', value: 1 },
  { name: 'New Orleans', value: 1 },
  { name: 'New York', value: 8 },
  { name: 'Normal (IL)', value: 1 },
  { name: 'North Beach', value: 1 },
  { name: 'North East Lakeside', value: 1 },
  { name: 'North Oak Park', value: 1 },
  { name: 'Oak Park', value: 2 },
  { name: 'Old Irving Park', value: 1 },
  { name: 'Park Slope', value: 1 },
  { name: 'Philadelphia', value: 1 },
  { name: 'Pittsburgh', value: 1 },
  { name: 'Portland', value: 1 },
  { name: 'Pullman (Wa)', value: 1 },
  { name: 'Richmond (VA)', value: 3 },
  { name: 'Rural Elton (LA)', value: 1 },
  { name: 'Sacramento', value: 6 },
  { name: 'Saint Paul', value: 1 },
  { name: 'San Francisco', value: 2 },
  { name: 'San Jose', value: 1 },
  { name: 'Santa Fe', value: 1 },
  { name: 'Sarasota', value: 1 },
  { name: 'Saugatuck', value: 1 },
  { name: 'Seattle', value: 1 },
  { name: 'Somerville (MA)', value: 1 },
  { name: 'South Buffalo', value: 1 },
  { name: 'South Burlington (VT)', value: 1 },
  { name: 'South Oak Park', value: 1 },
  { name: 'South Philadelphia', value: 1 },
  { name: 'Southeast Portland', value: 1 },
  { name: 'Spring Hill', value: 1 },
  { name: 'Stockton', value: 1 },
  { name: 'Suburban Kansas City', value: 1 },
  { name: 'Tecopa', value: 1 },
  { name: 'The Bronx', value: 2 },
  { name: 'Washington Heights', value: 1 },
  { name: 'Westcliffe (CO)', value: 1 },
  { name: 'Wrigleyvalue', value: 1 },
]

export const VISIT_COUNT = [
  { name: "not sure / hard to say", value: "0.04" },
  { name: "0", value: "0.396" },
  { name: "1-2", value: "0.188" },
  { name: "3-5", value: "0.178" },
  { name: "5-10", value: "0.069" },
  { name: "10-25", value: "0.069" },
  { name: "25+", value: "0.069" },
];

export const VISIT_PRIORITY = [
  { name: "not sure / hard to say", value: "0.059" },
  { name: "extremely important", value: "0.149" },
  { name: "somewhat important", value: "0.257" },
  { name: "not important", value: "0.525" },
];

export const COLLECTOR_TREATMENT = [
  { name: "not sure / hard to say", value: "0.061" },
  { name: "did not sell work", value: "0.143" },
  { name: "extremely positive", value: "0.344" },
  { name: "generally positive", value: "0.378" },
  { name: "neutral / mixed", value: "0.051" },
  { name: "generally poor", value: "0.02" },
  { name: "extremely poor", value: "0.00" },
];

export const SALES_MEDIUMS = [
  { name: "Paintings",	value: 42 },
  { name: "T-Shirts",	value: 14 },
  { name: "Prints",	value: 13 },
  { name: "Drawings",	value: 11 },
  { name: "Stickers",	value: 7 },
  { name: "Pins",	value: 4 },
  { name: "Books",	value: 3 },
  { name: "Mixed Media",	value: 3 },
  { name: "Sketches",	value: 3 },
  { name: "Zines",	value: 3 },
  { name: "Cards",	value: 2 },
  { name: "Designs",	value: 2 },
  { name: "Digital Prints",	value: 2 },
  { name: "Magnets",	value: 2 },
  { name: "Photographs",	value: 2 },
  { name: "Sculpture",	value: 2 },
];

export const SALES_SUM = [
  { name: "$0", value: "0.14" },
  { name: "$1-$50", value: "0.13" },
  { name: "$50-$250", value: "0.13" },
  { name: "$250-$500", value: "0.14" },
  { name: "$500-$1,000", value: "0.16" },
  { name: "$1,000-$2,500", value: "0.12" },
  { name: "$2,500-$5,000", value: "0.13" },
  { name: "$5,000-$10,000", value: "0.01" },
  { name: "$10,000-$25,000", value: "0.01" },
  { name: "$25,000-$50,000", value: "0.02" },
  { name: "$$50,000+", value: "0.01" },
];

export const ANY_ONLINE_SALES = [
  { name: "no", value: "0.633" },
  { name: "yes", value: "0.367" },
];

export const SALE_PLATFORMS = [
  { name: "No Online Sales", value: (63 / 101) },
  { name: "Etsy", value: (11 / 101) },
  { name: "Saatchi Art", value: (3 / 101) },
  { name: "Art Finder", value: (2 / 101) },
  { name: "BigCartel", value: (2 / 101) },
  { name: "Red Bubble", value: (2 / 101) },
  { name: "Art in Context", value: (1 / 101) },
  { name: "Artery", value: (1 / 101) },
  { name: "Artsy", value: (1 / 101) },
  { name: "Bandcamp", value: (1 / 101) },
  { name: "Deviantart", value: (1 / 101) },
  { name: "SquareUp", value: (1 / 101) },
  { name: "Facebook", value: (1 / 101) },
  { name: "Fine Art America", value: (1 / 101) },
  { name: "Fiverr", value: (1 / 101) },
  { name: "Instagram", value: (1 / 101) },
  { name: "Padel 8", value: (1 / 101) },
  { name: "Personal Website", value: (1 / 101) },
  { name: "Printful", value: (1 / 101) },
  { name: "Square Space", value: (1 / 101) },
  { name: "Wix", value: (1 / 101) },
  { name: "Wordpress Website", value: (1 / 101) },
]

export const BUYERS_CLOUD = [
  { name: 'Amateur / New Collectors', value: 35 },
  { name: 'Art Center Store In Consignment', value: 1 },
  { name: 'Artomat Machines', value: 1 },
  { name: 'Book Fair', value: 2 },
  { name: 'BFA / MFA Peers', value: 8 },
  { name: 'Established / Experienced Collectors', value: 20 },
  { name: 'Event Attendants', value: 1 },
  { name: 'Event Attendees', value: 31 },
  { name: 'Family / Friends', value: 62 },
  { name: 'Former / Current Faculty', value: 7 },
  { name: 'Gallerists / Curators', value: 6 },
  { name: 'Gallery Clients', value: 1 },
  { name: 'I Don’t Sell My Art', value: 1 },
  { name: 'Interior Designer For Client', value: 1 },
  { name: 'My Financial Advisor', value: 1 },
  { name: 'Nobody', value: 1 },
  { name: 'None', value: 2 },
  { name: 'Online Fans', value: 31 },
  { name: 'Other Artists', value: 34 },
  { name: 'Strangers', value: 1 },
  { name: 'Youtubers (Animation Assets)', value: 1 },
]

export const SELLLING_PRIORITY = [
  { name: "Not Sure / Hard to Say", value: "0.03" },
  { name: "Not Important", value: "0.202" },
  { name: "Somewhat Important", value: "0.434" },
  { name: "Extremely Important", value: "0.323" },
];

export const GRANT_SUM = [
  { name: "no applications", value: "0.51" },
  { name: "$0", value: "0.39" },
  { name: "$1-$500", value: "0.02" },
  { name: "$500-$5,000", value: "0.07" },
  { name: "$5,000-$15,000", value: "0.01" },
];

export const GRANT_COUNT = [
  { name: "no applications", value: "0.55" },
  { name: "0", value: "0.34" },
  { name: "1-2", value: "0.11" },
];

export const GRANT_APP_COUNT = [
  { name: "0", value: "0.713" },
  { name: "1-2", value: "0.218" },
  { name: "3-5", value: "0.059" },
  { name: "", value: "0.01" },
];

export const RESIDENCY_COUNT = [
  { name: "no applications", value: "0.475" },
  { name: "0", value: "0.434" },
  { name: "1-2", value: "0.091" },
]

export const RESIDENCY_APP_COUNT = [
  { name: "0", value: "0.723" },
  { name: "1-2", value: "0.218" },
  { name: "3-5", value: "0.05" },
  { name: "6-10", value: "0.01" },
]

export const RESIDENCY_PRIORITY = [
  { name: "Not Sure / Hard to Say", value: "0.112" },
  { name: "Not Important", value: "0.49" },
  { name: "Somewhat Important", value: "0.286" },
  { name: "Extremely Important", value: "0.112" },
];

export const LEGAL_PAPERWORK = [
  { name: "no", value: "0.624" },
  { name: "yes (with explaination)", value: "0.287" },
  { name: "yes (not fully explained)", value: "0.059" },
  { name: "not sure / don't recall", value: "0.03" },
]

export const GALLERY_REPRESENTATION = [
  { name: "no", value: "0.83" },
  { name: "yes", value: "0.17" },
]

export const EVENT_ORGANIZATION = [
  { name: "0", value: "0.554" },
  { name: "1", value: "0.178" },
  { name: "2", value: "0.129" },
  { name: "3", value: "0.079" },
  { name: "4", value: "0.02" },
  { name: "5+", value: "0.04" },
]

export const COLORS = [
  "rgb(216, 159, 202)",
  "rgb(247, 193, 209)",
  "#FFB7B2",
  "rgb(252, 210, 183)",
  "rgb(188, 223, 132)",
  "rgb(166, 226, 204)",
  "rgb(158, 171, 226)",
]

export const EXHIBITION_CONTACT = [
    { name: 'Art Council Research', value: (1 / 201) },
    { name: 'Non Profit Gallery', value: (1 / 201) },
    { name: 'Art Societies', value: (2 / 201) },
    { name: 'BFA / MFA Peers', value: (15 / 201) },
    { name: 'Cold Contacting Spaces', value: (12 / 201) },
    { name: 'Contacts from Facebook', value: (11 / 201) },
    { name: 'Contacts from Instagram', value: (27 / 201) },
    { name: 'Direct Contact At An Art Center', value: (1 / 201) },
    { name: 'Direct Emails from Gallerists / Curators', value: (23 / 201) },
    { name: 'Friends', value: (1 / 201) },
    { name: 'Gallery Represented', value: (1 / 201) },
    { name: 'Group Invitationals', value: (1 / 201) },
    { name: 'N/A', value: (2 / 201) },
    { name: 'Open Call On Instagram', value: (1 / 201) },
    { name: 'Other Artists', value: (50 / 201) },
    { name: 'Relationships With Spaces', value: (1 / 201) },
    { name: 'Structured Applications', value: (37 / 201) },
    { name: 'Open Calls', value: (37 / 201) },
    { name: 'Teachers / Faculty', value: (15 / 201) },
]

export const SOCMEDIA_FEATURES = [
  { name: "Not Sure / Hard to Say", value: "0.071" },
  { name: "0", value: "0.163" },
  { name: "1-2", value: "0.214" },
  { name: "3-5", value: "0.265" },
  { name: "6-10", value: "0.071" },
  { name: "11-25", value: "0.112" },
  { name: "25+", value: "0.102" },
]

export const PUBLICATION_COUNT = [
  { name: "0", value: "0.584" },
  { name: "1-2", value: "0.287" },
  { name: "3-5", value: "0.099" },
  { name: "6-10", value: "0.02" },
  { name: "11-25", value: "0" },
  { name: "25+", value: "0.01" },
]

export const APPLICATION_FEES = [
  { name: "Not Sure / Hard to Say", value: "0.01" },
  { name: "$0", value: "0.44" },
  { name: "$0-$25", value: "0.08" },
  { name: "$25-$50", value: "0.13" },
  { name: "$50-$100", value: "0.13" },
  { name: "$100-$250", value: "0.15" },
  { name: "$250+", value: "0.06" },
];

export const SHOW_APPLICATIONS = [
  { name: "0", value: "0.416" },
  { name: "1-2", value: "0.178" },
  { name: "3-5", value: "0.218" },
  { name: "6-10", value: "0.139" },
  { name: "11-25", value: "0.03" },
  { name: "25+", value: "0.02" },
];

export const SOLO_EXHIBITIONS_COUNT = [
  { name: "0", value: "0.673" },
  { name: "1-2", value: "0.297" },
  { name: "3-5", value: "0.3" },
];

export const GROUP_EXHIBITIONS_COUNT = [
  { name: "0", value: "0.228" },
  { name: "1-2", value: "0.475" },
  { name: "3-5", value: "0.218" },
  { name: "6-10", value: "0.079" },
];

export const EXHIBITIONS_PRIORITY = [
  { name: "Extremely Important", value: "0.218" },
  { name: "Somewhat Important", value: "0.465" },
  { name: "Not Important", value: "0.228" },
  { name: "Not Sure / Hard to Say", value: "0.079" },
];

export const RACE = [
  { name: "Decline to Answer", value: "0.04" },
  { name: "White / Caucasian", value: "0.73" },
  { name: "Biracial / Multi Racial", value: "0.07" },
  { name: "Asian / Asian American", value: "0.04" },
  { name: "Black / African American", value: "0.04" },
  { name: "Jewish / White", value: "0.03" },
  { name: "Latino / Latina / Latinx", value: "0.03" },
  { name: "Iranian", value: "0.01" },
  { name: "Native American", value: "0.01" },
];

export const GENDER = [
  { name: "Other", value: "0.005" },
  { name: "Non-Binary", value: "0.08" },
  { name: "Male", value: "0.32" },
  { name: "Female", value: "0.58" },
];

export const AGE = [
  { name: "<18", value: "0.06" },
  { name: "18-29", value: "0.32" },
  { name: "30-39", value: "0.26" },
  { name: "40-49", value: "0.07" },
  { name: "50-59", value: "0.09" },
  { name: "60-69", value: "0.14" },
  { name: "70+", value: "0.06" },
];

export const ORIENTATION = [
  { name: "Yes", value: "0.564" },
  { name: "No", value: "0.356" },
  { name: "Decline to Say", value: "0.079" },
];

export const FOUND_SURVEY = [
  { name: "artist / peer", value: "0.198" },
  { name: "instagram", value: "0.733" },
  { name: "other", value: "0.069" },
];

export const KEYWORDS = [
  { name: "Abstract", value: 23 },
  { name: "Abstracted", value: 1 },
  { name: "Abstraction", value: 5 },
  { name: "Acid", value: 1 },
  { name: "Acrylic", value: 11 },
  { name: "Acrylics", value: 1 },
  { name: "Aesthetics", value: 1 },
  { name: "Age", value: 1 },
  { name: "Alien", value: 1 },
  { name: "Allegorical", value: 1 },
  { name: "Altars", value: 1 },
  { name: "Altered", value: 1 },
  { name: "Anatomy", value: 1 },
  { name: "Anger", value: 1 },
  { name: "Animal", value: 1 },
  { name: "Animals", value: 1 },
  { name: "Animation", value: 3 },
  { name: "Anthropomorphic", value: 1 },
  { name: "Art", value: 4 },
  { name: "Archetypes", value: 1 },
  { name: "Architectural", value: 1 },
  { name: "Artist", value: 1 },
  { name: "Arts", value: 1 },
  { name: "Assemblage", value: 1 },
  { name: "Astrology", value: 1 },
  { name: "Authentic", value: 1 },
  { name: "Auto", value: 1 },
  { name: "Background", value: 1 },
  { name: "Banality", value: 1 },
  { name: "Baroque", value: 1 },
  { name: "Based", value: 1 },
  { name: "Biology", value: 1 },
  { name: "Biomorphic", value: 1 },
  { name: "Black", value: 1 },
  { name: "Board", value: 1 },
  { name: "Body", value: 1 },
  { name: "Bold", value: 1 },
  { name: "Books", value: 1 },
  { name: "Botanical", value: 2 },
  { name: "Bright", value: 9 },
  { name: "Brush", value: 1 },
  { name: "Brutality", value: 1 },
  { name: "Building", value: 1 },
  { name: "Carving", value: 1 },
  { name: "Ceramic", value: 1 },
  { name: "Chance", value: 1 },
  { name: "Change", value: 1 },
  { name: "Character", value: 1 },
  { name: "Characters", value: 1 },
  { name: "Charcoal", value: 3 },
  { name: "Caricatures", value: 1 },
  { name: "Cinematic", value: 1 },
  { name: "Classical", value: 2 },
  { name: "Clay", value: 1 },
  { name: "Climate", value: 1 },
  { name: "Cold", value: 2 },
  { name: "Collage", value: 4 },
  { name: "Colo", value: 1 },
  { name: "Color", value: 14 },
  { name: "Colored", value: 1 },
  { name: "Colorful", value: 14 },
  { name: "Colorist", value: 1 },
  { name: "Colors", value: 5 },
  { name: "Colour", value: 2 },
  { name: "Comic", value: 1 },
  { name: "Conceptua", value: 1 },
  { name: "Conceptual", value: 4 },
  { name: "Concerns", value: 1 },
  { name: "Concrete", value: 1 },
  { name: "Confrontational", value: 1 },
  { name: "Connections", value: 1 },
  { name: "Consciousness", value: 1 },
  { name: "Contemporary", value: 5 },
  { name: "Contour", value: 1 },
  { name: "Contrasting", value: 1 },
  { name: "Cosmic", value: 1 },
  { name: "Craft", value: 1 },
  { name: "Cultural", value: 1 },
  { name: "Cyberpunk", value: 1 },
  { name: "Dark", value: 1 },
  { name: "Depth", value: 1 },
  { name: "Design", value: 3 },
  { name: "Detailed", value: 1 },
  { name: "Different", value: 1 },
  { name: "Digital", value: 4 },
  { name: "Discord", value: 1 },
  { name: "Discrimination", value: 1 },
  { name: "Disfigured", value: 1 },
  { name: "Divide", value: 1 },
  { name: "Documentary", value: 1 },
  { name: "Dot", value: 1 },
  { name: "Drama", value: 1 },
  { name: "Drawing", value: 14 },
  { name: "Drawings", value: 2 },
  { name: "Dreams", value: 1 },
  { name: "Dynami", value: 1 },
  { name: "Dystopia", value: 1 },
  { name: "Earth", value: 1 },
  { name: "Earthy", value: 1 },
  { name: "Ecology", value: 3 },
  { name: "Edgy", value: 1 },
  { name: "Education", value: 1 },
  { name: "Embodiment", value: 1 },
  { name: "Emotional", value: 1 },
  { name: "Emphasis", value: 1 },
  { name: "Endangered", value: 1 },
  { name: "Endurance", value: 1 },
  { name: "Environmental", value: 3 },
  { name: "Ephemeral", value: 1 },
  { name: "Erotic", value: 1 },
  { name: "Ethnography", value: 1 },
  { name: "Existential", value: 2 },
  { name: "Experimenta", value: 1 },
  { name: "Experimental", value: 2 },
  { name: "Exploration", value: 2 },
  { name: "Explorations", value: 1 },
  { name: "Expression", value: 1 },
  { name: "Expressionist", value: 1 },
  { name: "Expressionistic", value: 1 },
  { name: "Expressive", value: 4 },
  { name: "Family", value: 1 },
  { name: "Fan", value: 1 },
  { name: "Fantastical", value: 1 },
  { name: "Fantasy", value: 1 },
  { name: "Fears", value: 1 },
  { name: "Feeling", value: 1 },
  { name: "Fiber", value: 1 },
  { name: "Fibers", value: 1 },
  { name: "Fiction", value: 2 },
  { name: "Field", value: 1 },
  { name: "Figurative", value: 21 },
  { name: "Film", value: 1 },
  { name: "Finishes", value: 1 },
  { name: "Flashe", value: 1 },
  { name: "Folk", value: 1 },
  { name: "Form", value: 3 },
  { name: "Formal", value: 2 },
  { name: "Fragile", value: 1 },
  { name: "Fun", value: 1 },
  { name: "Functional", value: 1 },
  { name: "Game", value: 2 },
  { name: "Geometric", value: 2 },
  { name: "Glaze", value: 1 },
  { name: "Gouache", value: 1 },
  { name: "Graphic", value: 2 },
  { name: "Graphite", value: 7 },
  { name: "Grotesque", value: 1 },
  { name: "Hairy", value: 1 },
  { name: "Hard", value: 1 },
  { name: "Harmony", value: 2 },
  { name: "Hate", value: 1 },
  { name: "Healing", value: 1 },
  { name: "Health", value: 2 },
  { name: "High", value: 1 },
  { name: "High Chroma", value: 1 },
  { name: "History", value: 2 },
  { name: "Hope", value: 1 },
  { name: "Horror", value: 1 },
  { name: "Hubris", value: 1 },
  { name: "Human", value: 3 },
  { name: "Humorou", value: 1 },
  { name: "Hurt", value: 1 },
  { name: "Illustration", value: 2 },
  { name: "Image", value: 1 },
  { name: "Imaginative", value: 1 },
  { name: "Ink", value: 6 },
  { name: "Inking", value: 1 },
  { name: "Intaglio", value: 1 },
  { name: "Interactions", value: 1 },
  { name: "Interactive", value: 2 },
  { name: "Interdisciplinar", value: 2 },
  { name: "Interdisciplinary", value: 7 },
  { name: "Intimacy", value: 1 },
  { name: "Intimate", value: 1 },
  { name: "Introspective", value: 1 },
  { name: "Intuitive", value: 2 },
  { name: "Irreverent", value: 1 },
  { name: "Issue", value: 1 },
  { name: "Issues", value: 9 },
  { name: "Japanese", value: 1 },
  { name: "Justice", value: 1 },
  { name: "Knife", value: 1 },
  { name: "Landscape", value: 7 },
  { name: "Large-Scale", value: 1 },
  { name: "Layered", value: 1 },
  { name: "Layering", value: 1 },
  { name: "Life", value: 3 },
  { name: "Light", value: 2 },
  { name: "Line", value: 1 },
  { name: "Linear", value: 1 },
  { name: "Literary", value: 1 },
  { name: "Loneliness", value: 1 },
  { name: "Loss", value: 1 },
  { name: "Love", value: 2 },
  { name: "Luminous", value: 1 },
  { name: "Magic", value: 1 },
  { name: "Manga", value: 1 },
  { name: "Markers", value: 1 },
  { name: "Material", value: 1 },
  { name: "Materialit", value: 1 },
  { name: "Mathematics", value: 1 },
  { name: "Mature", value: 1 },
  { name: "Maximalism", value: 1 },
  { name: "Media", value: 3 },
  { name: "Medias", value: 1 },
  { name: "Medium/Large", value: 1 },
  { name: "Mediums", value: 1 },
  { name: "Memory", value: 2 },
  { name: "Mental", value: 2 },
  { name: "Metal", value: 2 },
  { name: "Minimal", value: 2 },
  { name: "Minimalis", value: 1 },
  { name: "Minimalism", value: 2 },
  { name: "Minimalist", value: 1 },
  { name: "Minority", value: 1 },
  { name: "Misunderstood", value: 1 },
  { name: "Mix", value: 1 },
  { name: "Mixed-Media", value: 16 },
  { name: "Monochrome", value: 1 },
  { name: "Monotone", value: 1 },
  { name: "Moody", value: 1 },
  { name: "Motion", value: 1 },
  { name: "Multi", value: 1 },
  { name: "Multi-Disciplinary", value: 1 },
  { name: "Multicolors", value: 1 },
  { name: "Multidisciplinary", value: 1 },
  { name: "Multimedia", value: 1 },
  { name: "Multiple", value: 1 },
  { name: "Multiples", value: 1 },
  { name: "Mural", value: 1 },
  { name: "Music", value: 1 },
  { name: "Mute", value: 1 },
  { name: "Muted", value: 2 },
  { name: "Mystical", value: 1 },
  { name: "Mysticism", value: 2 },
  { name: "Myth", value: 2 },
  { name: "Mythology", value: 1 },
  { name: "Narration", value: 1 },
  { name: "Narrative", value: 5 },
  { name: "Natural", value: 1 },
  { name: "Nature", value: 4 },
  { name: "Neon", value: 1 },
  { name: "Neons", value: 1 },
  { name: "New", value: 1 },
  { name: "Night", value: 1 },
  { name: "Non-Objective", value: 2 },
  { name: "Nostalgic", value: 1 },
  { name: "Obscurification", value: 1 },
  { name: "Obsolete", value: 1 },
  { name: "Often", value: 1 },
  { name: "Oil", value: 15 },
  { name: "Oils", value: 1 },
  { name: "Opaque", value: 1 },
  { name: "Organic", value: 3 },
  { name: "Others", value: 1 },
  { name: "Outlet", value: 1 },
  { name: "Pain", value: 1 },
  { name: "Paint", value: 9 },
  { name: "Painter", value: 2 },
  { name: "Painterly", value: 2 },
  { name: "Painting", value: 19 },
  { name: "Paintings", value: 4 },
  { name: "Paints", value: 2 },
  { name: "Palette", value: 1 },
  { name: "Panel", value: 1 },
  { name: "Paper", value: 6 },
  { name: "Pastel", value: 1 },
  { name: "Pattern", value: 1 },
  { name: "Patterned", value: 1 },
  { name: "Pen", value: 1 },
  { name: "Pencil", value: 3 },
  { name: "Penciled", value: 1 },
  { name: "Pencils", value: 1 },
  { name: "Performance", value: 1 },
  { name: "Performative", value: 1 },
  { name: "Performativity", value: 1 },
  { name: "Personal", value: 4 },
  { name: "Photo", value: 2 },
  { name: "Photograph", value: 1 },
  { name: "Photography", value: 7 },
  { name: "Photoremi", value: 1 },
  { name: "Pink", value: 1 },
  { name: "Plants", value: 2 },
  { name: "Pluralism", value: 1 },
  { name: "Poetics", value: 1 },
  { name: "Polish", value: 1 },
  { name: "Political", value: 4 },
  { name: "Pop", value: 1 },
  { name: "Portrait", value: 3 },
  { name: "Portraits", value: 3 },
  { name: "Portraiture", value: 1 },
  { name: "Precious", value: 1 },
  { name: "Press", value: 1 },
  { name: "Print", value: 1 },
  { name: "Printmaking", value: 5 },
  { name: "Prints", value: 1 },
  { name: "Processing", value: 1 },
  { name: "Provoking", value: 1 },
  { name: "Psyche", value: 1 },
  { name: "Psychoanalytical", value: 1 },
  { name: "Psychology", value: 2 },
  { name: "Queer", value: 2 },
  { name: "Questions", value: 1 },
  { name: "Quiet", value: 1 },
  { name: "Racial", value: 1 },
  { name: "Realism", value: 2 },
  { name: "Realist", value: 1 },
  { name: "Realistic", value: 2 },
  { name: "Reality", value: 1 },
  { name: "Relational", value: 1 },
  { name: "Relationships", value: 1 },
  { name: "Religion", value: 1 },
  { name: "Representation", value: 1 },
  { name: "Representational", value: 2 },
  { name: "Repurpose", value: 1 },
  { name: "Research", value: 2 },
  { name: "Responsibility", value: 1 },
  { name: "Rights", value: 2 },
  { name: "Saturation", value: 1 },
  { name: "Scale", value: 1 },
  { name: "Schizophrenia", value: 1 },
  { name: "School", value: 1 },
  { name: "Sci-Fi", value: 2 },
  { name: "Science", value: 5 },
  { name: "Scissor", value: 1 },
  { name: "Screen", value: 1 },
  { name: "Screenprinting", value: 1 },
  { name: "Sculptor", value: 1 },
  { name: "Sculpture", value: 10 },
  { name: "Sculptural", value: 3 },
  { name: "Sculptures", value: 1 },
  { name: "Semi-Abstract", value: 1 },
  { name: "Semi-Realism", value: 1 },
  { name: "Series", value: 1 },
  { name: "Sexual", value: 1 },
  { name: "Shapes", value: 3 },
  { name: "Silhouette", value: 1 },
  { name: "Single", value: 1 },
  { name: "Sketch", value: 1 },
  { name: "Social", value: 10 },
  { name: "Society", value: 2 },
  { name: "Socio-Political", value: 1 },
  { name: "Soft", value: 1 },
  { name: "Sound", value: 2 },
  { name: "Space", value: 3 },
  { name: "Spectrality", value: 1 },
  { name: "Spiritual", value: 5 },
  { name: "Spirituality", value: 1 },
  { name: "Steampunk", value: 1 },
  { name: "Still", value: 2 },
  { name: "Still-Life", value: 2 },
  { name: "Stitching", value: 1 },
  { name: "Story", value: 2 },
  { name: "Stream", value: 1 },
  { name: "Styleless", value: 1 },
  { name: "Styles", value: 1 },
  { name: "Stylized", value: 2 },
  { name: "Subject", value: 1 },
  { name: "Subjugation", value: 1 },
  { name: "Supremacy", value: 1 },
  { name: "Surreal", value: 2 },
  { name: "Surrealism", value: 2 },
  { name: "Surrealist", value: 2 },
  { name: "Symbolism", value: 1 },
  { name: "Taking", value: 1 },
  { name: "Tattoo", value: 1 },
  { name: "Technical", value: 1 },
  { name: "Technique", value: 1 },
  { name: "Techno", value: 1 },
  { name: "Telling", value: 1 },
  { name: "Tension", value: 1 },
  { name: "Text", value: 1 },
  { name: "Textile", value: 1 },
  { name: "Textiles", value: 1 },
  { name: "Textural", value: 1 },
  { name: "Texture", value: 1 },
  { name: "Theme", value: 1 },
  { name: "Theory", value: 1 },
  { name: "Thought", value: 1 },
  { name: "Tonalism", value: 1 },
  { name: "Tones", value: 1 },
  { name: "Traditional", value: 2 },
  { name: "Trangender", value: 1 },
  { name: "Trans", value: 1 },
  { name: "Transfer", value: 1 },
  { name: "Transien", value: 1 },
  { name: "Transparency", value: 1 },
  { name: "Unconventional", value: 1 },
  { name: "Underdeveloped", value: 1 },
  { name: "Unique", value: 1 },
  { name: "Unstable", value: 1 },
  { name: "Urban", value: 1 },
  { name: "Variety", value: 1 },
  { name: "Vector", value: 1 },
  { name: "Vectors", value: 1 },
  { name: "Video", value: 2 },
  { name: "Views", value: 1 },
  { name: "Vintage", value: 1 },
  { name: "Visibility", value: 1 },
  { name: "Visual", value: 1 },
  { name: "Vivid", value: 2 },
  { name: "Water", value: 3 },
  { name: "Watercolor", value: 5 },
  { name: "Watercolour", value: 1 },
  { name: "Wax", value: 1 },
  { name: "Wearable", value: 1 },
  { name: "Weaving", value: 1 },
  { name: "Web", value: 1 },
  { name: "Whimsical", value: 1 },
  { name: "White", value: 1 },
  { name: "Women", value: 1 },
  { name: "Woo", value: 1 },
  { name: "Wood", value: 3 },
  { name: "Words", value: 1 },
  { name: "Works", value: 1 },
  { name: "World", value: 1 },
  { name: "Writing", value: 1 },
  { name: "Zines", value: 2 },
];


export const EXHIBITION_SPACES = [
  { name: "Art Center", value: 1 },
  { name: "Art Fair", value: 1 },
  { name: "Art School Galleries", value: 1 },
  { name: "Art Walks", value: 1 },
  { name: "Artist Run Spaces", value: 44 },
  { name: "Beauty Salons", value: 1 },
  { name: "Book Fairs", value: 2 },
  { name: "Church", value: 1 },
  { name: "Co-op Spaces", value: 12 },
  { name: "Coffee Shops", value: 16 },
  { name: "College Gallery", value: 1 },
  { name: "Furniture Store", value: 1 },
  { name: "Gallery Spaces", value: 52 },
  { name: "Library", value: 1 },
  { name: "Museum Spaces", value: 19 },
  { name: "None", value: 1 },
  { name: "Nonprofit Wellness / Creative Center", value: 1 },
  { name: "Open Studio", value: 2 },
  { name: "Outdoor Spaces", value: 10 },
  { name: "Podcast Episode", value: 1 },
  { name: "Pop-Up Spaces", value: 16 },
  { name: "Public Spaces", value: 25 },
  { name: "Restaurants", value: 2 },
  { name: "School", value: 1 },
  { name: "Schools", value: 1 },
  { name: "State Fair", value: 1 },
  { name: "Tavern", value: 1 },
  { name: "Theater", value: 1 },
  { name: "Universities and Colleges", value: 1 },
]